import Layout from "../components/Layout";

export function Privacy() {
  return <Layout title="Privacy"><LegalShell eyebrow="Governance · Privacy" title="Privacy"><p>EndureLuxe Limited is the intended controller for EndureLuxe programme and website data. The current preview has no live registration backend configured unless a production registration endpoint is explicitly connected.</p><h2>What the founding form asks for</h2><p>First name, email, optional city/country, acknowledgement of the health disclaimer and a separate optional marketing choice. The v1 form deliberately does not request medical history, diagnoses, weight or other health information.</p><h2>Purpose boundaries</h2><p>Programme contact is used to administer or discuss EndureLuxe participation. Marketing consent is separate and optional. EndureLuxe participant data is not automatically shared with Abraham of London or Alomarada merely because the businesses share a founder or related ownership interests.</p><h2>Processors</h2><p>This policy must be updated before launch to name any hosting, registration, payment, email or analytics providers actually connected. No processor is claimed here merely because an integration is available.</p><h2>Your rights</h2><p>Applicable UK data-protection rights may include access, correction, erasure, restriction, objection and portability. Production contact details and retention periods must be confirmed before live data collection begins.</p></LegalShell></Layout>;
}

export function Terms() {
  return <Layout title="Terms"><LegalShell eyebrow="Governance · Terms" title="Terms of use"><p>The EndureLuxe site provides general information about physical capability, consistency and the proposed The 45 programme. This preview does not currently accept payment.</p><h2>Programme scope</h2><p>The 45 is a general fitness-consistency programme, not medical treatment, clinical exercise prescription or a guarantee of weight loss, appearance change or other outcome.</p><h2>Founding price</h2><p>The displayed £99 price is an introductory founding-cohort price, not a fabricated discount. Full purchase, cancellation and refund terms must be presented before any live checkout is activated.</p><h2>Use of content</h2><p>EndureLuxe writing, programme structures, design and branding may not be republished or commercially exploited without permission, subject to rights that cannot lawfully be restricted.</p><h2>Changes</h2><p>These preview terms will be replaced with a launch version once payment, registration and service-delivery infrastructure is actually configured.</p></LegalShell></Layout>;
}

export function HealthDisclaimer() {
  return <Layout title="Health disclaimer"><LegalShell eyebrow="Health boundary" title="Health disclaimer"><p>EndureLuxe provides general fitness, movement, consistency and accountability information. It does not diagnose, treat or prevent medical conditions and is not a substitute for advice from an appropriately qualified healthcare or fitness professional.</p><h2>Before activity</h2><p>Choose activity appropriate to your own circumstances. Seek medical or professional advice before starting or changing exercise where appropriate, particularly if you have symptoms, a known health condition, recent injury, pregnancy or other circumstances that may affect safe participation.</p><h2>During activity</h2><p>Stop activity and seek appropriate medical attention if you experience concerning symptoms such as chest pain, fainting, severe shortness of breath, sudden neurological symptoms or another response that causes concern. In an emergency, use the appropriate emergency service.</p><h2>No performance guarantee</h2><p>Individual responses to physical activity vary. EndureLuxe does not guarantee fitness, body-composition, health or performance outcomes.</p></LegalShell></Layout>;
}

function LegalShell({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) {
  return <article className="legal-page section-pad"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><div className="legal-body">{children}</div></article>;
}
